// LOGIN ACTIONS
export const LOGGING_IN = "LOGGINGIN";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const FAIL_LOGIN = "FAIL_LOGIN";
export const SET_USER = "SET_USER";
export const SET_AUTH = "SET_AUTH";
export const LOG_OUT = "LOG_OUT";

// SIGN UP ACTIONS
export const SIGNING_UP = "SIGNING_UP";
export const SUCCESS_SIGN_UP = "SUCCESS_SIGN_UP";
export const FAIL_SIGN_UP = "FAIL_SIGN_UP";

// GROUP ACTIONS
export const CREATING_GROUP = "CREATING_GROUP";
export const SUCCESS_CREATE_GROUP = "SUCCESS_CREATE_GROUP";
export const FAIL_CREATE_GROUP = "FAIL_CREATE_GROUP";

export const GETTING_GROUPS = "GETTING_GROUPS";
export const SUCCESS_GET_GROUPS = "SUCCESS_GET_GROUPS";
export const FAIL_GET_GROUPS = "FAIL_GET_GROUPS";

export const DELETEING_GROUP = "DELETEING_GROUP";
export const SUCCESS_DELETE_GROUP = "SUCCESS_DELETE_GROUP";
export const FAIL_DELETE_GROUP = "FAIL_DELETE_GROUP";

export const SET_VIEWING_GROUP = "SET_VIEWING_GROUP";
// ORGANIZATION ACTIONS
export const GETTING_ORGANIZATIONS = "GETTING_ORGANIZATIONS";
export const SUCCESS_GETTING_ORGANIZATIONS = "SUCCESS_GETTING_ORGANIZATIONS";
export const FAIL_GETTING_ORGANIZATIONS = "FAIL_GETTING_ORGANIZATIONS";

export const CREATING_ORGANIZATION = "CREATING_ORGANIZATION";
export const SUCCESS_CREATE_ORGANIZATION = "SUCCESS_CREATE_ORGANIZATION";
export const FAIL_CREATE_ORGANIZATION = "FAIL_CREATE_ORGANIZATION";

export const JOINING_ORGANIZATION = "JOINING_ORGANIZATION";
export const SUCCESS_JOIN_ORGANIZATION = "SUCCESS_JOIN_ORGANIZATION";
export const FAIL_JOIN_ORGANIZATIONS = "FAIL_JOIN_ORGANIZATIONS";

// MEMBER BOX ACTIONS
export const GETTING_CONTACTS = "GET_CONTACTS";
export const SUCCESS_GETTING_CONTACTS = "SUCCESS_GETTING_CONTACTS";
export const FAIL_GETTING_CONTACTS = "FAIL_GETTING_CONTACTS";

export const CREATING_CONTACT = "CREATE_CONTACT";
export const SUCCESS_CREATING_CONTACT = "SUCCESS_CREATING_CONTACT";
export const FAIL_CREATING_CONTACT = "FAIL_CREATING_CONTACT";

export const DELETING_CONTACT = "DELETING_CONTACT";
export const SUCCESS_DELETING_CONTACT = "SUCCESS_DELETING_CONTACT";
export const FAIL_DELETING_CONTACT = "FAIL_DELETING_CONTACT";

export const REPLACE_CONTACTS = "REPLACE_CONTACTS";

//MESSAGE ACTIONS

export const SENDING_MESSAGE = "SENDING_MESSAGE";
export const SUCCESS_SENDING_MESSAGE = "SUCCESS_SENDING_MESSAGE";
export const FAIL_SENDING_MESSAGE = "FAIL_SENDING_MESSAGE";

export const GETTING_MESSAGES = "GETTING_MESSAGES";
export const SUCCESS_GETTING_MESSAGES = "SUCCESS_GETTING_MESSAGES";
export const FAIL_GETTING_MESSAGES = "FAIL_GETTING_MESSAGES";

export const DRAFTING_MESSAGE = "DRAFTING_MESSAGE";
export const SUCCESS_DRAFTING_MESSAGE = "SUCCESS_DRAFTING_MESSAGE";
export const FAIL_DRAFTING_MESSAGE = "FAIL_DRAFTING_MESSAGE";

export const DELETING_MESSAGE = "DELETING_MESSAGE"
export const SUCCESS_DELETING_MESSAGE = "SUCCESS_DELETING_MESSAGE"
export const FAIL_DELETING_MESSAGE = "FAIL_DELETING_MESSAGE"

export const SET_MESSAGE = "SET_MESSAGE";
export const UPDATE_INPUT_MESSAGE = "UPDATE_INPUT_MESSAGE";
export const CLEAR_LOCAL_MESSAGES = 'CLEAR_LOCAL_MESSAGES';

//SCHEDULE ACTIONS

export const SCHEDULING_MESSAGE = 'SCHEDULING_MESSAGE'
export const SUCCESS_SCHEDULING_MESSAGE = 'SUCCESS_SCHEDULING_MESSAGE'
export const FAIL_SCHEDULING_MESSAGE = 'FAIL_SCHEDULING_MESSAGE' 

export const GETTING_SCHEDULED_MESSAGES = 'GETTING_SCHEDULED_MESSAGES'
export const SUCCESS_GETTING_SCHEDULED_MESSAGES = 'SUCCESS_GETTING_SCHEDULED_MESSAGES'
export const FAIL_GETTING_SCHEDULED_MESSAGES = 'FAIL_GETTING_SCHEDULED_MESSAGES'

export const DELETING_SCHEDULED_MESSAGES = 'DELETING_SCHEDULED_MESSAGES'
export const SUCCESS_DELETING_SCHEDULED_MESSAGES = 'SUCCESS_DELETING_SCHEDULED_MESSAGES'
export const FAIL_DELETING_SCHEDULED_MESSAGES = 'FAIL_DELETING_SCHEDULED_MESSAGES'

export const CLEAR_LOCAL_SCHEDULED_MESSAGES = 'CLEAR_LOCAL_SCHEDULED_MESSAGES'