// LOGIN ACTIONS
export const LOGGING_IN = "LOGGINGIN";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const FAIL_LOGIN = "FAIL_LOGIN";
export const SET_USER = "SET_USER";

export const LOG_OUT = "LOG_OUT";
// SIGN UP ACTIONS
export const SIGNING_UP = "SIGNING_UP";
export const SUCCESS_SIGN_UP = "SUCCESS_SIGN_UP";
export const FAIL_SIGN_UP = "FAIL_SIGN_UP";
// GROUP ACTIONS
export const CREATING_GROUP = "CREATING_GROUP";
export const SUCCESS_CREATE_GROUP = "SUCCESS_CREATE_GROUP";
export const FAIL_CREATE_GROUP = "FAIL_CREATE_GROUP";

export const DELETEING_GROUP = "DELETEING_GROUP";
export const SUCCESS_DELETE_GROUP = "SUCCESS_DELETE_GROUP";
export const FAIL_DELETE_GROUP = "FAIL_DELETE_GROUP";

// ORGANIZATION ACTIONS

export const GETTING_ORGANIZATIONS = "GETTING_ORGANIZATIONS";
export const SUCCESS_GETTING_ORGANIZATIONS = "SUCCESS_GETTING_ORGANIZATIONS";
export const FAIL_GETTING_ORGANIZATIONS = "FAIL_GETTING_ORGANIZATIONS";
